name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-apk:
    name: Build debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install npm dependencies
        run: npm ci

      - name: Build web assets (Vite)
        run: npm run build

      - name: Copy web assets into Android (Capacitor)
        run: npx cap copy android

      - name: Ensure Android platform exists and show diagnostics
        run: |
          echo "-- repo root listing --"
          ls -la
          echo "-- dist listing --"
          ls -la dist || true
          echo "-- capacitor config --"
          cat capacitor.config.ts || cat capacitor.config.json || true
          if [ ! -d android ]; then
            echo "android/ not found — adding platform"
            npx cap add android
          else
            echo "android/ exists"
          fi
          echo "-- android listing --"
          ls -la android || true
          npx cap ls || true

      - name: Set up Java (Temurin 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          target: android-33
          components: platforms;android-33,build-tools;33.0.2,platform-tools

      - name: Build APK (assembleDebug)
        working-directory: android
        run: ./gradlew assembleDebug --no-daemon --stacktrace --info

      - name: Upload debug APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
